<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '"{attribute}" must be a valid JSON object' => '',
    'Active' => '',
    'Created' => '',
    'Friday' => '星期五',
    'ID' => '',
    'Key' => '',
    'Modified' => '',
    'Get Verify Code' => '获取验证码',
    'Monday' => '星期一',
    'Please select correct type' => '',
    'Saturday' => '星期六',
    'Section' => '',
    'Sunday' => '星期日',
    'Thursday' => '星期四',
    'Tuesday' => '星期二',
    'Type' => '',
    'Value' => '',
    'Wednesday' => '星期三',
    '{attribute} "{value}" already exists for this section.' => '',
    '{attribute} Do not meet the rules.' => '',
];
